services:
  postgres:
    image: postgres:16-alpine
    container_name: app-tomy-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: tomy
      POSTGRES_PASSWORD: tomy1234
      POSTGRES_DB: app_tomy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
